### ISSUE TITLE
DirectoryNotFoundException

### ISSUE THREAD

**Issue by ibuckshot5** [Kopernicus/Stellarator#5]
Every time I use stellarator and select the name and stuff, it opens in Microsoft Visual Studio and says there is a DirectoryNotFoundException.

Exception detail:

`System.IO.DirectoryNotFoundException was unhandled
  HResult=-2147024893
  Message=Could not find a part of the path 'C:\Stellarator-master\Stellarator-master\Distribution\data\starnames'.
  Source=mscorlib
  StackTrace:
       at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
       at System.IO.FileSystemEnumerableIterator`1.CommonInit()
       at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
       at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
       at Stellarator.Utility.Load(String foldername) in C:\Stellarator-master\Stellarator-master\Source\Utility.cs:line 160
       at Stellarator.Utility.GenerateStarName() in C:\Stellarator-master\Stellarator-master\Source\Utility.cs:line 246
       at Stellarator.Generator.GenerateSun(SolarSystem system, String folder, Boolean systematicNames) in C:\Stellarator-master\Stellarator-master\Source\Generator.cs:line 126
       at Stellarator.Generator.Generate(String seed, String folder, Boolean systematicNames) in C:\Stellarator-master\Stellarator-master\Source\Generator.cs:line 72
       at Stellarator.Program.Main(String[] args) in C:\Stellarator-master\Stellarator-master\Source\Program.cs:line 50
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
`

**Comment by MartinX3** [comment]
Do you still get this error?
I checked out my fork, compiled it and generated a system.
I don't get this error.
